<?php

/**
 * Implements hook_language_switch_links_alter().
 *
 * Replaces links with pointers to translated versions of the content.
 */
function searchapi_i18n_links_block_language_switch_links_alter(array &$links, $type, $path) {
  static $is_execute_filter_switch_link;
  if ($search = search_api_current_search() && !isset($is_execute_filter_switch_link)) {
    $is_execute_filter_switch_link = true;

    $searcher = facetapi_terms_get_search_info_index();
    $adapter = facetapi_adapter_load($searcher);
    $adapter->processFacets();
    $facets = $adapter->getEnabledFacets();

    // get All active items.
    $allActiveItems = $adapter->getAllActiveItems();
    if(!empty($allActiveItems)) return;
    
    $process = new FacetapiUrlProcessorPrettyPaths($adapter);

    global $language;
    foreach ($links as $lancode => &$link) {
      if ($language->language == $lancode)
        continue;
      $paths = array();
      foreach ($allActiveItems as $item) {
        $facet = $facets[$item['facets'][0]];
        // get term tranlation id.
        $tvalue = searchapi_i18n_links_block_get_field_item($item['field alias'], $item['value'], $lancode);
        $path = $process->getFacetPath($facet, array($tvalue), 0);
        $paths[] = trim($path);
      }
      // get base path TODO:
      $process->fetchParams();
      array_unshift($paths, $process->getBasePath());
      $links[$lancode]['href'] = implode('', $paths);
    }
  }
}

// get term tranlation id.
function searchapi_i18n_links_block_get_field_item($field, $search_id, $lancode) {
  $field_array = explode(':', $field);
  $field = $bundle = false;
  if (count($field_array) > 1) {
    list($bundle, $field) = $field_array;
  }
  else {
    $field = $field_array[0];
  }
  $field_info = field_info_field($field);
  switch ($field_info['type']) {
    case "taxonomy_term_reference":
      $term = taxonomy_term_load($search_id);
      $tterm = i18n_taxonomy_term_get_translation($term, $lancode);
      $tvalue = $tterm->tid;
      break;
    case "node_reference":
      if($tn = translation_node_get_translations(node_load($search_id)->tnid)) {
        $tvalue = $tn[$lancode]->nid;
      }
      break;
  }
  
  return $tvalue;
}
